#!/usr/bin/env python3
"""
generate_hinglish_audio.py

Synthesizes speech for Hinglish dialogue lines generated by DeepSeek
using F5-TTS with voice cloning from a master reference audio file.

Audio Resampling: Resamples to 22,050 Hz, 16-bit PCM, mono using soundfile + soxr (no ffmpeg needed).

Prerequisites:
  1. F5-TTS installed: pip install f5-tts
  2. Master reference audio & transcript:
     - master_references/cloned_indian_tutor_master.wav (approx 5-10s clean audio)
"""

import argparse
from pathlib import Path
import shutil
import subprocess
import sys

import numpy as np
import soundfile as sf
import soxr


def resample_to_piper_spec(wav_path: Path) -> None:
    """Resamples strictly to 22,050 Hz, Mono, 16-bit PCM for Piper TTS."""
    data, sr = sf.read(str(wav_path), dtype="float32")
    if data.ndim > 1:
        data = np.mean(data, axis=1)  # convert to mono
    if sr != 22050:
        data = soxr.resample(data, sr, 22050, quality="MQ")
    arr: np.ndarray = np.ascontiguousarray(data, dtype=np.float32)
    sf.write(str(wav_path), arr, 22050, subtype="PCM_16")  # type: ignore[arg-type]


def find_cli_tool(cli_tool: str = "f5-tts_infer-cli") -> str | None:
    # Check PATH first
    found = shutil.which(cli_tool)
    if found:
        return found
    # Check .venv/bin/ directory alongside active python
    venv_bin = Path(sys.executable).parent / cli_tool
    if venv_bin.exists():
        return str(venv_bin)
    return None


def check_prerequisites(cli_tool_path: str | None, ref_audio: Path) -> bool:
    all_ok = True
    if not cli_tool_path:
        print(
            "ERROR: 'f5-tts_infer-cli' command not found!\n"
            "To install F5-TTS in your environment, run:\n"
            "  pip install f5-tts\n",
            file=sys.stderr,
        )
        all_ok = False

    if not ref_audio.exists():
        print(
            f"ERROR: Reference audio '{ref_audio}' does not exist!\n"
            "Please place a 5-10 second clean reference WAV clip of the Indian tutor voice at:\n"
            f"  {ref_audio.resolve()}\n",
            file=sys.stderr,
        )
        all_ok = False

    return all_ok


def run_f5_tts_pipeline(
    metadata_file: Path,
    output_audio_dir: Path,
    ref_audio_path: Path,
    ref_text: str,
    device: str = "cpu",
    cli_tool: str = "f5-tts_infer-cli",
):
    if not metadata_file.exists():
        print(f"Error: Metadata file '{metadata_file}' not found. Run generate_hinglish_text.py first.", file=sys.stderr)
        sys.exit(1)

    cli_tool_path = find_cli_tool(cli_tool)
    if not cli_tool_path or not check_prerequisites(cli_tool_path, ref_audio_path):
        sys.exit(1)
    assert cli_tool_path is not None

    output_audio_dir.mkdir(parents=True, exist_ok=True)
    success_count = 0
    failure_count = 0

    with open(metadata_file, "r", encoding="utf-8") as f:
        lines = [line.strip() for line in f if line.strip() and "|" in line]

    total = len(lines)
    print(f"Starting F5-TTS voice synthesis for {total} utterances...")
    print(f"  - Using F5-TTS CLI: {cli_tool_path}")
    print(f"  - Reference Audio: {ref_audio_path}")
    print(f"  - Reference Text: '{ref_text}'")
    print(f"  - Device: {device}")
    print(f"  - Target Output Dir: {output_audio_dir.resolve()}\n")

    for idx, line in enumerate(lines, 1):
        file_id, tts_text = line.split("|", 1)
        output_wav_path = output_audio_dir / f"{file_id}.wav"

        if output_wav_path.exists() and output_wav_path.stat().st_size > 1000:
            print(f"[{idx}/{total}] Skipping {file_id} (already generated)")
            success_count += 1
            continue

        print(f"[{idx}/{total}] Synthesizing {file_id}: \"{tts_text[:50]}...\"")

        command = [
            cli_tool_path,
            "--device", device,
            "--gen_text", tts_text,
            "--ref_audio", str(ref_audio_path),
            "--ref_text", ref_text,
            "--output_dir", str(output_audio_dir),
            "--output_file", f"{file_id}.wav",
        ]

        try:
            res = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            if res.returncode != 0:
                print(f"  [ERROR] F5-TTS failed on {file_id}: {res.stderr.strip()}", file=sys.stderr)
                failure_count += 1
                continue

            if output_wav_path.exists():
                resample_to_piper_spec(output_wav_path)
                success_count += 1
            else:
                print(f"  [WARNING] Output file {output_wav_path} not found after generation.")
                failure_count += 1
        except Exception as e:
            print(f"  [ERROR] Execution failed for {file_id}: {e}", file=sys.stderr)
            failure_count += 1

    print("\n" + "=" * 50)
    print(f"Synthesis Complete: {success_count} succeeded, {failure_count} failed.")
    print("=" * 50)


def main():
    parser = argparse.ArgumentParser(description="Synthesize Hinglish audio using F5-TTS voice cloning.")
    parser.add_argument(
        "--metadata",
        type=Path,
        default=Path("dataset_output/metadata.txt"),
        help="Path to metadata.txt (file_id|text)",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("dataset_output/wavs"),
        help="Directory to save generated WAV files",
    )
    parser.add_argument(
        "--ref-audio",
        type=Path,
        default=Path("master_references/cloned_indian_tutor_master.wav"),
        help="Master reference audio WAV file for voice cloning",
    )
    parser.add_argument(
        "--ref-text",
        type=str,
        default=None,
        help="Exact transcript of the reference audio clip. If not passed, checks for a .txt file with the same name as ref-audio.",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="cpu",
        help="Compute device for inference (default: cpu for stable macOS execution)",
    )
    args = parser.parse_args()

    ref_text = args.ref_text
    ref_txt_file = args.ref_audio.with_suffix(".txt")
    if not ref_text:
        if ref_txt_file.exists():
            ref_text = ref_txt_file.read_text(encoding="utf-8").strip()
            print(f"Loaded reference transcript from: {ref_txt_file}")
        else:
            ref_text = "afterwords the teacher from navgurukul decided to do a class project with Abhishek to see what kind of impact the recognition would have on the community."
            print(f"[NOTE] Using default reference text. For custom text, pass --ref-text or create {ref_txt_file}")

    run_f5_tts_pipeline(args.metadata, args.output_dir, args.ref_audio, ref_text, device=args.device)


if __name__ == "__main__":
    main()
